name: afrilingo
description: A language learning app for African languages
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'  # Updated to support super-parameters

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.3
  shared_preferences: ^2.2.2  # Use the latest stable version
  flutter_dotenv: ^5.1.0
  percent_indicator: ^4.2.3 
  dart_openai: ^2.0.0 
  # Added percent_indicator package
  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - assets/facebook_icon.png
    - lib/images/Screenshot 2025-02-03 192844.png
    - lib/images/profile.jpg
  #   - images/a_dot_ham.jpeg
